jobs:
  add-to-project:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ITEM_ADD }}
      if: ${{ github.event.label.name == 'good first issue' }}
      name: good first issue
      run: 'ISSUE_URL=$(jq --raw-output .issue.html_url "$GITHUB_EVENT_PATH")

        gh project item-add 5 --owner JabRef --url $ISSUE_URL

        '
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ITEM_ADD }}
      if: github.event.label.name == 'needs-refinement'
      name: needs-refinement
      run: 'ISSUE_URL=$(jq --raw-output .issue.html_url "$GITHUB_EVENT_PATH")

        gh project item-add 15 --owner JabRef --url $ISSUE_URL

        '
    - continue-on-error: true
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ITEM_ADD }}
      if: '${{ github.event.label.name == ''status: freeze'' }}'
      name: 'status: freeze'
      run: 'ISSUE_URL=$(jq --raw-output .issue.html_url "$GITHUB_EVENT_PATH")

        gh project item-add 9 --owner JabRef --url $ISSUE_URL

        '
    - continue-on-error: true
      env:
        GH_DEBUG: api
        GH_TOKEN: ${{ secrets.GH_TOKEN_PROJECT_ITEM_ADD }}
      if: ${{ github.event.label.name == 'ui' }}
      name: ui
      run: 'ISSUE_URL=$(jq --raw-output .issue.html_url "$GITHUB_EVENT_PATH")

        echo $ISSUE_URL

        gh project item-add 8 --owner JabRef --url $ISSUE_URL

        '
name: Add to Project on Label
on:
  repository_dispatch:
    types: trigger-ga___add-to-projects.yml
permissions:
  issues: write
