jobs:
  GreetingFirstTimeCodeContribution:
    if: ${{ github.event.label.name == 'FirstTimeCodeContribution' }}
    permissions:
      issues: write
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: GreetingFirstTimeCodeContribution
      uses: peter-evans/create-or-update-comment@v4
      with:
        body: "Welcome to the vibrant world of open-source development with JabRef!\n\
          \nNewcomers, we're excited to have you on board. Start by exploring our\
          \ [Contributing](https://github.com/JabRef/jabref/blob/main/CONTRIBUTING.md)\
          \ guidelines, and don't forget to check out our [workspace setup guidelines](https://devdocs.jabref.org/getting-into-the-code/guidelines-for-setting-up-a-local-workspace)\
          \ to get started smoothly.\n\nHaving any questions or issues? Feel free\
          \ to ask here on GitHub. Need help setting up your local workspace? Join\
          \ the conversation on [JabRef's Gitter chat](https://gitter.im/JabRef/jabref).\
          \ And don't hesitate to open a (draft) pull request early on to show the\
          \ direction it is heading towards. This way, you will receive valuable feedback.\n\
          \nHappy coding! \U0001F680\n"
        issue-number: ${{ github.event.issue.number || github.event.pull_request.number
          }}
name: Add greeting to issues for first time contributors
on:
  repository_dispatch:
    types: trigger-ga___add-greeting-to-issue.yml
