jobs:
  automerge:
    if: "(github.repository == 'JabRef/jabref') &&  (github.event.pull_request.head.repo.full_name\
      \ == 'JabRef/jabref') && (\n  (github.actor == 'dependabot[bot]') ||\n  (\n\
      \    startsWith(github.event.pull_request.title, '[Bot] ') || \n    startsWith(github.event.pull_request.title,\
      \ 'Bump ') || \n    startsWith(github.event.pull_request.title, 'New Crowdin\
      \ updates') ||\n    startsWith(github.event.pull_request.title, 'Update Gradle\
      \ Wrapper from')\n  )\n)\n"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN_JABREF_MACHINE_PR_APPROVE}}
        PR_URL: ${{github.event.pull_request.html_url}}
      name: Approve PR
      run: gh pr review --approve "$PR_URL"
    - continue-on-error: true
      env:
        GITHUB_TOKEN: ${{secrets.GH_TOKEN_UPDATE_GRADLE_WRAPPER}}
        PR_URL: ${{github.event.pull_request.html_url}}
      name: Merge PR
      run: gh pr merge --auto --squash "$PR_URL"
name: Auto Merge
on:
  repository_dispatch:
    types: trigger-ga___automerge.yml
permissions:
  contents: write
  pull-requests: write
