concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
jobs:
  lychee:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
    - continue-on-error: true
      name: Restore lychee cache
      uses: actions/cache@v4
      with:
        key: cache-lychee-${{ github.sha }}
        path: .lycheecache
        restore-keys: cache-lychee-
    - continue-on-error: true
      id: lychee
      name: Link Checker
      uses: lycheeverse/lychee-action@v1.10.0
      with:
        args: --accept '200,201,202,203,204,403,429,500' --max-concurrency 1 --cache
          --no-progress --exclude-all-private './**/*.md'
        fail: true
name: Check external href links in the documentation
on:
  repository_dispatch:
    types: trigger-ga___check-links.yml
