jobs:
  cleanup:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Cancel deployment run
      uses: styfle/cancel-workflow-action@0.12.1
      with:
        ignore_sha: true
        workflow_id: 9813
    - continue-on-error: true
      env:
        BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      id: checksecrets
      name: Check secrets presence
      run: "if [ \"$BUILDJABREFPRIVATEKEY\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      if: steps.checksecrets.outputs.secretspresent == 'YES'
      name: Delete folder on builds.jabref.org
      uses: appleboy/ssh-action@v1.0.3
      with:
        host: build-upload.jabref.org
        key: ${{ secrets.buildJabRefPrivateKey }}
        port: 9922
        script: rm -rf /var/www/builds.jabref.org/www/pull/${{ github.event.pull_request.number
          }} || true
        username: jrrsync
    - continue-on-error: true
      if: steps.checksecrets.outputs.secretspresent == 'YES'
      name: Update PR comment
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: download-link
        message: The build for this PR is no longer available. Please visit <https://builds.jabref.org/main/>
          for the latest build.
        mode: upsert
name: Cleanup after PR
on:
  repository_dispatch:
    types: trigger-ga___cleanup-pr.yml
