concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
env:
  AstrophysicsDataSystemAPIKey: ${{ secrets.AstrophysicsDataSystemAPIKey }}
  BiodiversityHeritageApiKey: ${{ secrets.BiodiversityHeritageApiKey}}
  GRADLE_OPTS: -Xmx4g -Dorg.gradle.vfs.watch=false
  IEEEAPIKey: ${{ secrets.IEEEAPIKey }}
  JAVA_OPTS: -Xmx4g
  OSXCERT: ${{ secrets.OSX_SIGNING_CERT }}
  SpringerNatureAPIKey: ${{ secrets.SpringerNatureAPIKey }}
jobs:
  announce:
    if: ${{ github.event_name == 'pull_request' }}
    name: Comment on pull request
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      id: checksecrets
      name: Check secrets presence
      run: "if [ \"$BUILDJABREFPRIVATEKEY\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent == 'YES')
      name: Comment PR
      uses: thollander/actions-comment-pull-request@v2
      with:
        comment_tag: download-link
        message: 'The build of this PR is available at <https://builds.jabref.org/pull/${{
          github.event.pull_request.number }}/merge>.

          '
        mode: recreate
  build:
    name: ${{ matrix.displayName }} installer and portable version
    outputs:
      branchname: ${{ steps.gitversion.outputs.branchName }}
      major: ${{ steps.gitversion.outputs.Major }}
      minor: ${{ steps.gitversion.outputs.Minor }}
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      id: checksecrets
      name: Check secrets presence
      run: "if [ \"$BUILDJABREFPRIVATEKEY\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      name: Fetch all history for all tags and branches
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      if: (matrix.os == 'ubuntu-latest')
      name: Install pigz and cache (linux)
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: pigz
        version: 1.0
    - continue-on-error: true
      name: Install GitVersion
      uses: gittools/actions/gitversion/setup@v1.1.1
      with:
        versionSpec: 5.x
    - continue-on-error: true
      id: gitversion
      name: Run GitVersion
      uses: gittools/actions/gitversion/execute@v1.1.1
    - continue-on-error: true
      name: Setup JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') || (steps.checksecrets.outputs.secretspresent
        == 'NO')
      name: Prepare merged jars and modules dir (macOS)
      run: ./gradlew -i -PprojVersion="${{ steps.gitversion.outputs.AssemblySemVer
        }}" -PprojVersionInfo="${{ steps.gitversion.outputs.InformationalVersion }}"
        prepareModulesDir
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Setup macOS key chain
      uses: slidoapp/import-codesign-certs@1923310662e8682dd05b76b612b53301f431cd5d
      with:
        keychain-password: jabref
        p12-file-base64: ${{ secrets.OSX_SIGNING_CERT }}
        p12-password: ${{ secrets.OSX_CERT_PWD }}
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Setup macOS key chain for app id cert
      uses: slidoapp/import-codesign-certs@1923310662e8682dd05b76b612b53301f431cd5d
      with:
        create-keychain: false
        keychain-password: jabref
        p12-file-base64: ${{ secrets.OSX_SIGNING_CERT_APPLICATION }}
        p12-password: ${{ secrets.OSX_CERT_PWD }}
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Build dmg (macOS)
      run: 'jpackage \

        --module org.jabref/org.jabref.Launcher \

        --module-path ${{env.JAVA_HOME}}/jmods/:build/jlinkbase/jlinkjars \

        --add-modules org.jabref,org.jabref.merged.module  \

        --dest build/distribution \

        --app-content buildres/mac/jabrefHost.py \

        --app-content buildres/mac/native-messaging-host \

        --name JabRef \

        --app-version ${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }} \

        --verbose \

        --mac-sign \

        --vendor "JabRef e.V." \

        --mac-package-identifier JabRef \

        --mac-package-name JabRef \

        --type dmg --mac-signing-key-user-name "JabRef e.V. (6792V39SK3)" \

        --mac-package-signing-prefix org.jabref \

        --mac-entitlements buildres/mac/jabref.entitlements \

        --icon src/main/resources/icons/jabref.icns \

        --resource-dir buildres/mac \

        --file-associations buildres/mac/bibtexAssociations.properties \

        --jlink-options --bind-services \

        --java-options --add-exports=javafx.base/com.sun.javafx.event=org.jabref.merged.module
        \

        --java-options --add-exports=javafx.controls/com.sun.javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.graphics/javafx.scene=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control.skin=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/com.sun.javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref
        \

        --java-options --add-exports=javafx.base/com.sun.javafx.event=org.jabref \

        --java-options --add-exports=javafx.controls/com.sun.javafx.scene.control=org.jabref
        \

        --java-options --add-opens=javafx.graphics/javafx.scene=org.jabref \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref
        \

        --java-options --add-opens=javafx.controls/com.sun.javafx.scene.control=org.jabref

        '
      shell: bash
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Build pkg (macOS)
      run: 'jpackage \

        --module org.jabref/org.jabref.Launcher \

        --module-path ${{env.JAVA_HOME}}/jmods/:build/jlinkbase/jlinkjars \

        --add-modules org.jabref,org.jabref.merged.module  \

        --dest build/distribution \

        --app-content buildres/mac/jabrefHost.py \

        --app-content buildres/mac/native-messaging-host \

        --name JabRef \

        --app-version ${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }} \

        --verbose \

        --mac-sign \

        --vendor "JabRef e.V." \

        --mac-package-identifier JabRef \

        --mac-package-name JabRef \

        --type pkg --mac-signing-key-user-name "JabRef e.V. (6792V39SK3)" \

        --mac-package-signing-prefix org.jabref \

        --mac-entitlements buildres/mac/jabref.entitlements \

        --icon src/main/resources/icons/jabref.icns \

        --resource-dir buildres/mac \

        --file-associations buildres/mac/bibtexAssociations.properties \

        --jlink-options --bind-services \

        --java-options --add-exports=javafx.base/com.sun.javafx.event=org.jabref.merged.module
        \

        --java-options --add-exports=javafx.controls/com.sun.javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.graphics/javafx.scene=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control.skin=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/com.sun.javafx.scene.control=org.jabref.merged.module
        \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref
        \

        --java-options --add-exports=javafx.base/com.sun.javafx.event=org.jabref \

        --java-options --add-exports=javafx.controls/com.sun.javafx.scene.control=org.jabref
        \

        --java-options --add-opens=javafx.graphics/javafx.scene=org.jabref \

        --java-options --add-opens=javafx.controls/javafx.scene.control=org.jabref
        \

        --java-options --add-opens=javafx.controls/com.sun.javafx.scene.control=org.jabref

        '
      shell: bash
    - continue-on-error: true
      if: (matrix.os != 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Build runtime image and installer (linux, Windows)
      run: ./gradlew -i -PprojVersion="${{ steps.gitversion.outputs.AssemblySemVer
        }}" -PprojVersionInfo="${{ steps.gitversion.outputs.InformationalVersion }}"
        jpackage jlinkZip
      shell: bash
    - continue-on-error: true
      if: (matrix.os != 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Package application image (linux, Windows)
      run: ${{ matrix.archivePortable }}
      shell: bash
    - continue-on-error: true
      if: (matrix.os != 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Rename files
      run: 'get-childitem -Path build/distribution/* | rename-item -NewName {$_.name
        -replace "${{ steps.gitversion.outputs.AssemblySemVer }}","${{ steps.gitversion.outputs.Major
        }}.${{ steps.gitversion.outputs.Minor }}"}

        get-childitem -Path build/distribution/* | rename-item -NewName {$_.name -replace
        "portable","${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }}-portable"}

        '
      shell: pwsh
    - continue-on-error: true
      if: (matrix.os == 'ubuntu-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Repack deb file for Debian
      run: 'cd build/distribution

        ar x jabref_${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }}_amd64.deb

        zstd -d < control.tar.zst | xz > control.tar.xz

        zstd -d < data.tar.zst | xz > data.tar.xz

        ar -m -c -a sdsd jabref_${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }}_amd64_repackaged.deb debian-binary control.tar.xz data.tar.xz

        rm debian-binary control.tar.* data.tar.*

        mv -f jabref_${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }}_amd64_repackaged.deb jabref_${{ steps.gitversion.outputs.Major }}.${{ steps.gitversion.outputs.Minor
        }}_amd64.deb

        '
      shell: bash
    - continue-on-error: true
      if: ${{ (!startsWith(github.ref, 'refs/heads/gh-readonly-queue')) && (steps.checksecrets.outputs.secretspresent
        == 'YES') && ((matrix.os == 'macos-latest') && !((startsWith(github.ref, 'refs/tags/')
        || inputs.notarization == true))) }}
      name: Setup rsync (macOS)
      run: brew install rsync
    - continue-on-error: true
      if: (matrix.os == 'windows-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES') && (!startsWith(github.ref, 'refs/heads/gh-readonly-queue'))
      name: Setup rsync (Windows)
      run: choco install --no-progress rsync
    - continue-on-error: true
      if: ${{ (steps.checksecrets.outputs.secretspresent == 'YES') && (!startsWith(github.ref,
        'refs/heads/gh-readonly-queue')) && ((matrix.os != 'macos-latest') || !((startsWith(github.ref,
        'refs/tags/') || (inputs.notarization == true)))) }}
      name: Setup SSH key
      run: 'echo "${{ secrets.buildJabRefPrivateKey }}" > sshkey

        chmod 600 sshkey

        '
    - continue-on-error: true
      if: (matrix.os == 'windows-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES') && (!startsWith(github.ref, 'refs/heads/gh-readonly-queue'))
      name: Upload to builds.jabref.org (Windows)
      run: 'rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes
        --stats --rsync-path="mkdir -p /var/www/builds.jabref.org/www/${{ steps.gitversion.outputs.branchName
        }} && rsync" -e ''C:\ProgramData\chocolatey\lib\rsync\tools\bin\ssh.exe -p
        9922 -i sshkey -o StrictHostKeyChecking=no'' build/distribution/ jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{
        steps.gitversion.outputs.branchName }}/

        '
      shell: cmd
    - continue-on-error: true
      if: ${{ (!startsWith(github.ref, 'refs/heads/gh-readonly-queue')) && (steps.checksecrets.outputs.secretspresent
        == 'YES') && ((matrix.os == 'ubuntu-latest') || ((matrix.os == 'macos-latest')
        && !((startsWith(github.ref, 'refs/tags/') || inputs.notarization == true))))
        }}
      name: Upload to builds.jabref.org (linux, macOS)
      run: 'rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes
        --stats --rsync-path="mkdir -p /var/www/builds.jabref.org/www/${{ steps.gitversion.outputs.branchName
        }} && rsync" -e ''ssh -p 9922 -i sshkey -o StrictHostKeyChecking=no'' build/distribution/
        jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ steps.gitversion.outputs.branchName
        }}/

        '
      shell: bash
    - continue-on-error: true
      if: (matrix.os == 'macos-latest') && (steps.checksecrets.outputs.secretspresent
        == 'YES') && (startsWith(github.ref, 'refs/tags/') || inputs.notarization
        == true)
      name: Upload to GitHub workflow artifacts store (macOS)
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        name: JabRef-macOS-tbn
        path: build/distribution
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent != 'YES')
      name: Upload to GitHub workflow artifacts store
      uses: actions/upload-artifact@v4
      with:
        compression-level: 0
        name: JabRef-${{ matrix.os }}
        path: build/distribution
    strategy:
      fail-fast: false
      matrix:
        include:
        - archivePortable: tar -c -C build/distribution JabRef | pigz --rsyncable
            > build/distribution/JabRef-portable_linux.tar.gz && rm -R build/distribution/JabRef
          displayName: linux
          os: ubuntu-latest
        - archivePortable: 7z a -r build/distribution/JabRef-portable_windows.zip
            ./build/distribution/JabRef && rm -R build/distribution/JabRef
          displayName: windows
          os: windows-latest
        - displayName: macOS
          os: macos-latest
        os:
        - ubuntu-latest
        - windows-latest
        - macos-latest
  notarize:
    if: ${{ startsWith(github.ref, 'refs/tags/') || inputs.notarization == true }}
    name: macOS notarization
    needs:
    - build
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      env:
        BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      id: checksecrets
      name: Check secrets presence
      run: "if [ \"$BUILDJABREFPRIVATEKEY\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent == 'YES')
      name: Download from GitHub workflow artifacts store (macOS)
      uses: actions/download-artifact@master
      with:
        name: JabRef-macOS-tbn
        path: build/distribution/
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent == 'YES')
      name: Notarize dmg
      run: 'xcrun notarytool store-credentials "notarytool-profile" --apple-id "vorstand@jabref.org"
        --team-id "6792V39SK3" --password "${{ secrets.OSX_NOTARIZATION_APP_PWD }}"

        xcrun notarytool submit build/distribution/JabRef-${{ needs.build.outputs.major
        }}.${{ needs.build.outputs.minor }}.dmg --keychain-profile "notarytool-profile"
        --wait

        xcrun stapler staple build/distribution/JabRef-${{ needs.build.outputs.major
        }}.${{ needs.build.outputs.minor }}.dmg

        '
      shell: bash
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent == 'YES')
      name: Notarize pkg
      run: 'xcrun notarytool store-credentials "notarytool-profile" --apple-id "vorstand@jabref.org"
        --team-id "6792V39SK3" --password "${{ secrets.OSX_NOTARIZATION_APP_PWD }}"

        xcrun notarytool submit build/distribution/JabRef-${{ needs.build.outputs.major
        }}.${{ needs.build.outputs.minor }}.pkg --keychain-profile "notarytool-profile"
        --wait

        xcrun stapler staple build/distribution/JabRef-${{ needs.build.outputs.major
        }}.${{ needs.build.outputs.minor }}.pkg

        '
      shell: bash
    - continue-on-error: true
      if: (steps.checksecrets.outputs.secretspresent == 'YES')
      name: Upload to builds.jabref.org
      run: 'echo "${{ secrets.buildJabRefPrivateKey }}" > sshkey

        chmod 600 sshkey

        rsync -rt --chmod=Du=rwx,Dg=rx,Do=rx,Fu=rw,Fg=r,Fo=r --itemize-changes --stats
        --rsync-path="mkdir -p /var/www/builds.jabref.org/www/${{ needs.build.outputs.branchname
        }} && rsync" -e ''ssh -p 9922 -i sshkey -o StrictHostKeyChecking=no'' build/distribution/
        jrrsync@build-upload.jabref.org:/var/www/builds.jabref.org/www/${{ needs.build.outputs.branchname
        }}/

        '
      shell: bash
name: Deployment
on:
  repository_dispatch:
    types: trigger-ga___deployment.yml
