concurrency:
  cancel-in-progress: true
  group: gource
jobs:
  action:
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: 'false'
    - continue-on-error: true
      name: Development history of current build
      uses: BoundfoxStudios/action-gource@v2
      with:
        avatars_auto_fetch: true
        gource_file_filter: buildres/csl|\.csl
        gource_seconds_per_day: 1
        gource_start_date: '2024-04-01'
        gource_title: JabRef v5.14 (in development) | more information at contribute.jabref.org
        logo_url: https://www.jabref.org/img/JabRef-icon-256.png
    - continue-on-error: true
      name: Store video
      run: 'mkdir gource-videos

        mv ./gource/gource.mp4 ./gource-videos/jabref-v5.14-dev.mp4

        '
    - continue-on-error: true
      name: Development history of last release
      uses: BoundfoxStudios/action-gource@v2
      with:
        avatars_auto_fetch: true
        gource_file_filter: buildres/csl|\.csl
        gource_seconds_per_day: 2
        gource_start_date: '2023-12-24'
        gource_stop_date: '2024-04-01'
        gource_title: JabRef v5.13 | more information at contribute.jabref.org
        logo_url: https://www.jabref.org/img/JabRef-icon-256.png
    - continue-on-error: true
      name: Store video
      run: 'mv ./gource/gource.mp4 ./gource-videos/jabref-v5.13.mp4

        '
    - continue-on-error: true
      name: Complete development history
      uses: BoundfoxStudios/action-gource@v2
      with:
        avatars_auto_fetch: true
        gource_file_filter: buildres/csl|\.csl
        gource_seconds_per_day: 0.1
        gource_title: JabRef | more information at contribute.jabref.org
        logo_url: https://www.jabref.org/img/JabRef-icon-256.png
    - continue-on-error: true
      name: Store video
      run: 'mv gource/gource.mp4 gource-videos/jabref-complete.mp4

        '
    - continue-on-error: true
      name: Upload gource video
      uses: actions/upload-artifact@v4
      with:
        name: Gource
        path: gource-videos/
        retention-days: 80
    - continue-on-error: true
      env:
        BUILDJABREFPRIVATEKEY: ${{ secrets.buildJabRefPrivateKey }}
      id: checksecrets
      name: Check secrets presence
      run: "if [ \"$BUILDJABREFPRIVATEKEY\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      env:
        DEPLOY_KEY: ${{ secrets.buildJabRefPrivateKey }}
      if: steps.checksecrets.outputs.secretspresent == 'YES'
      name: Upload to files.jabref.org
      uses: Pendect/action-rsyncer@v2.0.0
      with:
        dest: jrrsync@build-upload.jabref.org:/var/www/files.jabref.org/www/gource/
        flags: -vaz --itemize-changes --stats --partial-dir=/tmp/partial
        options: ''
        src: gource-videos/
        ssh_options: -p 9922
name: Gource
on:
  repository_dispatch:
    types: trigger-ga___gource.yml
