concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
env:
  AstrophysicsDataSystemAPIKey: ${{ secrets.AstrophysicsDataSystemAPIKey_FOR_TESTS
    }}
  BiodiversityHeritageApiKey: ${{ secrets.BiodiversityHeritageApiKey_FOR_TESTS}}
  IEEEAPIKey: ${{ secrets.IEEEAPIKey_FOR_TESTS }}
  SpringerNatureAPIKey: ${{ secrets.SPRINGERNATUREAPIKEY_FOR_TESTS }}
jobs:
  fetchertests:
    name: Fetcher tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      env:
        CI: 'true'
      name: Run fetcher tests
      run: ./gradlew fetcherTest
name: Fetcher Tests
on:
  repository_dispatch:
    types: trigger-ga___tests-fetchers.yml
permissions:
  contents: read
