concurrency:
  cancel-in-progress: true
  group: ${{ github.workflow }}-${{ github.head_ref || github.ref }}
env:
  AstrophysicsDataSystemAPIKey: ${{ secrets.AstrophysicsDataSystemAPIKey }}
  BiodiversityHeritageApiKey: ${{ secrets.BiodiversityHeritageApiKey}}
  GRADLE_OPTS: -Xmx4g
  IEEEAPIKey: ${{ secrets.IEEEAPIKey }}
  JAVA_OPTS: -Xmx4g
  SpringerNatureAPIKey: ${{ secrets.SpringerNatureAPIKey }}
jobs:
  changelog:
    name: CHANGELOG.md
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'false'
    - continue-on-error: true
      name: Lint CHANGELOG.md
      run: '# Install jbang

        curl -Ls https://sh.jbang.dev | bash -s - app setup

        export PATH=$PATH:$HOME/.jbang/bin


        # run heylogs verification

        jbang com.github.nbbrd.heylogs:heylogs-cli:0.7.2:bin check CHANGELOG.md >
        heylogs.txt || true


        # improve output

        sed -i ''s/all-h2-contain-a-version/all-h2-contain-a-version (ignored)/''
        heylogs.txt


        cat heylogs.txt


        # exit 1 in case of error

        # We have 1 "valid" issue in CHANGELOG.md

        grep -q "1 problem" heylogs.txt || exit 1

        '
  changelog-unreleased-only:
    name: CHANGELOG.md - only unreleased touched
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        show-progress: 'false'
        submodules: 'false'
    - continue-on-error: true
      name: Install clparse
      run: 'curl -LO https://github.com/marcaddeo/clparse/releases/download/0.9.1/clparse-0.9.1-x86_64-unknown-linux-musl.tar.gz

        tar xzvf clparse-0.9.1-x86_64-unknown-linux-musl.tar.gz

        sudo mv clparse /usr/local/bin/clparse

        '
    - continue-on-error: true
      name: Check CHANGELOG.md diff
      run: "diff \\\n  <(git show origin/main:CHANGELOG.md | clparse --format=json\
        \ --separator=\u2013 - | jq '.releases[] | select(.version != null)') \\\n\
        \  <(git show HEAD:CHANGELOG.md | clparse --format=json --separator=\u2013\
        \ - | jq '.releases[] | select(.version != null)')\n"
  checkstyle:
    name: Checkstyle
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Run checkstyle reporter
      uses: nikitasavinov/checkstyle-action@master
      with:
        checkstyle_config: config/checkstyle/checkstyle_reviewdog.xml
        checkstyle_version: '10.3'
        github_token: ${{ secrets.GITHUB_TOKEN }}
        reporter: github-pr-review
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: Run checkstyle using gradle
      run: ./gradlew checkstyleMain checkstyleTest checkstyleJmh
  codecoverage:
    name: Code coverage
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres:10.8
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      id: checksecrets
      if: github.ref == 'refs/heads/main'
      name: Check secrets presence
      run: "if [ \"$CODECOV_TOKEN\" == \"\" ]; then\n  echo \"secretspresent=NO\"\
        \ >> $GITHUB_OUTPUT\nelse\n  echo \"secretspresent=YES\" >> $GITHUB_OUTPUT\n\
        fi\n"
      shell: bash
    - continue-on-error: true
      if: github.ref == 'refs/heads/main'
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      if: github.ref == 'refs/heads/main'
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      env:
        CI: 'true'
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
        DBMS: postgresql
      if: (github.ref == 'refs/heads/main') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      name: Update test coverage metrics
      run: xvfb-run --auto-servernum ./gradlew jacocoTestReport
    - continue-on-error: true
      if: (github.ref == 'refs/heads/main') && (steps.checksecrets.outputs.secretspresent
        == 'YES')
      uses: codecov/codecov-action@v4
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
  databasetests:
    name: Database tests
    runs-on: self-hosted
    services:
      postgres:
        env:
          POSTGRES_DB: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_USER: postgres
        image: postgres:13-alpine
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s
          --health-retries 5
        ports:
        - 5432:5432
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      env:
        CI: 'true'
        DBMS: postgresql
      name: Run tests on PostgreSQL
      run: ./gradlew databaseTest --rerun-tasks
    - continue-on-error: true
      name: Shutdown Ubuntu MySQL
      run: sudo service mysql stop
    - continue-on-error: true
      name: Start custom MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        character set server: utf8
        collation server: utf8_general_ci
        container port: 3307
        host port: 3800
        mysql database: jabref
        mysql root password: root
        mysql version: '8.0'
    - continue-on-error: true
      env:
        CI: 'true'
        DBMS: mysql
      name: Run tests on MySQL
      run: ./gradlew databaseTest --rerun-tasks
  gradlevalidation:
    name: Validate Gradle Wrapper
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
    - continue-on-error: true
      uses: gradle/wrapper-validation-action@v3
  guitests:
    name: GUI tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      env:
        CI: 'true'
      name: Run GUI tests
      run: xvfb-run --auto-servernum ./gradlew guiTest
  markdown:
    name: Markdown
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'false'
    - continue-on-error: true
      name: markdownlint-cli2-action
      uses: DavidAnson/markdownlint-cli2-action@v16
      with:
        globs: '*.md

          docs/**/*.md

          '
  merge_conflict_job:
    name: Find merge conflicts
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
    - continue-on-error: true
      name: Merge Conflict finder
      uses: olivernybroe/action-conflict-finder@v4.0
  modernizer:
    name: Modernizer
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: Run modernizer
      run: '# enable failing of this task if modernizer complains

        sed -i "s/failOnViolations = false/failOnViolations = true/" build.gradle

        ./gradlew modernizer

        '
  openrewrite:
    name: OpenRewrite
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      name: Run OpenRewrite
      run: './gradlew rewriteDryRun

        '
  other_than_main:
    name: Source branch is other than "main"
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      if: github.head_ref == 'main'
      uses: actions/github-script@v7
      with:
        script: "core.setFailed('Pull requests should come from a branch other than\
          \ \"main\"\\n\\n\U0001F449 Please read https://devdocs.jabref.org/contributing\
          \ again carefully. \U0001F448')\n"
  tests:
    name: Unit tests
    runs-on: self-hosted
    steps:
    - continue-on-error: true
      name: Checkout source
      uses: actions/checkout@v4
      with:
        show-progress: 'false'
        submodules: 'true'
    - continue-on-error: true
      name: Set up JDK
      uses: actions/setup-java@v4
      with:
        distribution: temurin
        java-version: 21.0.2
    - continue-on-error: true
      name: Setup Gradle
      uses: gradle/actions/setup-gradle@v3
      with:
        gradle-home-cache-cleanup: true
    - continue-on-error: true
      env:
        CI: 'true'
      name: Run tests
      run: xvfb-run --auto-servernum ./gradlew check -x checkstyleJmh -x checkstyleMain
        -x checkstyleTest -x modernizer
    - continue-on-error: true
      if: failure()
      name: Prepare format failed test results
      uses: awalsh128/cache-apt-pkgs-action@latest
      with:
        packages: xml-twig-tools xsltproc
        version: 1.0
    - continue-on-error: true
      if: failure()
      name: Format failed test results
      run: scripts/after-failure.sh
name: Tests
on:
  repository_dispatch:
    types: trigger-ga___tests.yml
permissions:
  pull-requests: write
